name: 'Create Status Comment'
description: 'Creates a comment with test coverage and check results'

inputs:
  coverage-data:
    description: 'Test coverage data in JSON format'
    required: true
  event-name:
    description: 'Name of the event (pull_request or push)'
    required: true
  issue-number:
    description: 'PR or Issue number'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Create Status Comment
      uses: actions/github-script@v7
      with:
        script: |
          const coverageData = JSON.parse(process.env.COVERAGE_DATA);
          const eventName = process.env.EVENT_NAME;

          const statusEmoji = eventName === 'push' ? '🚀' : '✅';
          const eventType = eventName === 'push' ? 'Merge to Master' : 'Pull Request';

          const comment = `${statusEmoji} ${eventType} Checks Completed Successfully!

          ## Coverage Report
          - Statements: ${coverageData.statements.pct}%
          - Branches: ${coverageData.branches.pct}%
          - Functions: ${coverageData.functions.pct}%
          - Lines: ${coverageData.lines.pct}%

          ## Check Results
          - ✅ Lint Check: Passed
          - ✅ Unit Tests: Passed
          `;

          github.rest.issues.createComment({
            issue_number: parseInt(process.env.ISSUE_NUMBER),
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: comment
          });
      env:
        COVERAGE_DATA: ${{ inputs.coverage-data }}
        EVENT_NAME: ${{ inputs.event-name }}
        ISSUE_NUMBER: ${{ inputs.issue-number }}
