name: Master Branch CI

on:
  push:
    branches: [master]

jobs:
  quality-checks:
    name: Quality Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run quality checks
        uses: ./.github/actions/quality-checks
        id: quality-checks

      - name: Find associated PR
        id: find-pr
        uses: actions/github-script@v7
        with:
          script: |
            const { data: prs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed',
              sort: 'updated',
              direction: 'desc',
              per_page: 1,
              head: `${context.repo.owner}:${context.ref.replace('refs/heads/', '')}`
            });
            return prs.length > 0 ? prs[0].number : null;
          result-encoding: string

      - name: Create status comment
        if: steps.find-pr.outputs.result != ''
        uses: ./.github/actions/create-status-comment
        with:
          coverage-data: ${{ steps.quality-checks.outputs.coverage-data }}
          event-name: 'push'
          issue-number: ${{ steps.find-pr.outputs.result }}
