name: Master Branch CI

on:
  push:
    branches: [master]

jobs:
  quality-checks:
    name: Quality Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run quality checks
        uses: ./.github/actions/quality-checks
        id: quality-checks

      - name: Post Success Summary
        run: |
          echo "✅ All quality checks passed successfully!"
          echo "Coverage: ${{ steps.quality-checks.outputs.coverage-data }}"
