name: Pull Request Checks

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]

jobs:
  quality-checks:
    name: Quality Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run quality checks
        uses: ./.github/actions/quality-checks
        id: quality-checks

      - name: Create status comment
        uses: ./.github/actions/create-status-comment
        with:
          coverage-data: ${{ steps.quality-checks.outputs.coverage-data }}
          event-name: 'pull_request'
          issue-number: ${{ github.event.pull_request.number }}
