name: Pull Request Checks

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]

jobs:
  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

  unit-tests:
    name: Unit Tests
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests with coverage
        run: npm run test -- --coverage

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
          retention-days: 7

  status-comment:
    name: PR Status Comment
    needs: [unit-tests]
    runs-on: ubuntu-latest
    if: always()
    steps:
      - uses: actions/checkout@v4

      - name: Download coverage report
        uses: actions/download-artifact@v4
        with:
          name: coverage-report
          path: coverage

      - name: Create Status Comment
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const coverageSummary = JSON.parse(fs.readFileSync('./coverage/coverage-summary.json', 'utf8'));

            const coverageData = {
              statements: coverageSummary.total.statements.pct,
              branches: coverageSummary.total.branches.pct,
              functions: coverageSummary.total.functions.pct,
              lines: coverageSummary.total.lines.pct
            };

            const statusEmoji = context.payload.pull_request.merged ? '🎉' : '✅';

            const comment = `${statusEmoji} Pull Request Checks Completed Successfully!

            ## Coverage Report
            - Statements: ${coverageData.statements}%
            - Branches: ${coverageData.branches}%
            - Functions: ${coverageData.functions}%
            - Lines: ${coverageData.lines}%

            ## Check Results
            - ✅ Lint Check: Passed
            - ✅ Unit Tests: Passed
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
