name: Pull Request Checks

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]

jobs:
  quality-checks:
    name: Quality Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run quality checks
        uses: ./.github/actions/quality-checks
        id: quality-checks
